### ISSUE TITLE
401 unauthorized - for password which works originally when fed into browser

### ISSUE THREAD

**Issue by geoHeil** [gouline/dbt-metabase#153]
I am getting a 401 unauthorized error now (not in the past). Perhaps something was broken in a release?

In any case: The same password works just fine when passed manually to the web UI of Metabase.

**Comment by geoHeil** [comment]
somehow the manual yaml script of the CI file (default config) is supplying wrong credentials. This is super strange.

**Comment by gouline** [comment]
We're authenticating daily on the latest version without issue, so must be something within your environment. 

Please only raise issues specifying exact steps and data to reproduce the problem, otherwise you're saying "please find something I couldn't find and fix what may or may not be there". Feel free to re-open this if you have those.
