### ISSUE TITLE
Unable to align models between dbt target models and Metabase

### ISSUE THREAD

**Issue by edbizarro** [gouline/dbt-metabase#166]
Hi,

After the release of https://github.com/gouline/dbt-metabase/pull/154 my `models` command fails and throws the error `Unable to align models between dbt target models and Metabase`, with `v0.9.13` i don't get this errors and the command finishes.

Is there a way, maybe a flag, to skip this behavior?

**Comment by gouline** [comment]
Yes, you can disable the `sync` flag.

**Comment by mandersoncruz** [comment]
I've been testing the `--metabase_sync_skip` flag, but since I have more models than the ones available in metabase, I still get the exception:
`dbtmetabase.models.exceptions.MetabaseRuntimeError: Model export encountered non-critical errors, check output`

As a solution, I started using `--dbt_includes`, but we may face operational issues due to many models. Can I have failed in using `dbt_includes`, but it doesn't accept the dbt tags pattern, only the model names, right?

Does it make sense to assume that if we use the `--metabase_sync_skip` flag, it would be acceptable to log but not raise an exception?

**Comment by subzet** [comment]
Hey! Ran into the same issue. We were using dbt-metabase 0.8.5 (really old:P) and decided to upgrade to 0.9.15 but that caused our dbt-metabase models sync to start failing.  What I've noticed is that you guys removed the flag that allowed the job to continue even with the sync failure. Why did you remove that? Would it be possible to add it again or I should go on without the sync? Thanks!!

**Comment by gouline** [comment]
Still there, just defaults to sync and you have to explicitly disable it.
