### ISSUE TITLE
Feature request: Ability to filter exposures based on data source/schema

### ISSUE THREAD

**Issue by mniyas** [gouline/dbt-metabase#295]
Feature Request: Filter Exposures by Data Source and Schema

Use Case: In Metabase, I manage multiple data sources. I aim to export only the dashboards that utilize dbt as their data source as exposures.

Proposal: Introduce filters to include or exclude specific data sources and schemas during the export process.

Benefits: This enhancement would streamline the exposure extraction, ensuring that only relevant dashboards are exported, thereby improving efficiency and relevance.

**Comment by gouline** [comment]
This would involve recursively traversing dependencies for each exposure. We check references (not recursively) for `depends_on` and it's unreliable even for that purpose, because of peculiarities in different types of queries (e.g. native SQL, questions querying other questions) and databases (e.g. BigQuery has no concept of schemas). Filtering exposures based on this is asking for bugs, which I don't think is feasible.

Best alternative I can think of is grouping your exposures in collections and filtering on that.
